const songs = [
  {
    title: "Suga Suga ft. Frankie J",
    artist: "Baby Bash",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Baby Bash - Suga Suga ft. Frankie J.mp3",
    id: 1,
  },
  {
    title: "Blitzkrieg Bop (Remastered Version)",
    artist: "Ramones",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Blitzkrieg Bop (Remastered Version).mp3",
    id: 2,
  },
  {
    title: "Runaway Baby [Official Lyric Video]",
    artist: "Bruno Mars",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Bruno Mars - Runaway Baby [Official Lyric Video].mp3",
    id: 3,
  },
  {
    title: "Feels (Official Video) ft. Pharrell Williams, Katy Perry, Big Sean",
    artist: "Calvin Harris",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Calvin Harris - Feels (Official Video) ft. Pharrell Williams, Katy Perry.mp3",
    id: 4,
  },
  {
    title: "Left And Right (feat. Jung Kook of BTS) [Official Video]",
    artist: "Charlie Puth",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Charlie Puth - Left And Right (feat. Jung Kook of BTS) [Official Video].mp3",
    id: 5,
  },
  {
    title: "Around The World (Official Video)",
    artist: "Daft Punk",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Daft Punk - Around The World (Official Video).mp3",
    id: 6,
  },
  {
    title: "On My Mind (Official Audio)",
    artist: "Diplo",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Diplo SIDEPIECE - On My Mind (Official Audio).mp3",
    id: 7,
  },
  {
    title: "The Next Episode ft. Snoop Dogg, Kurupt, Nate Dogg",
    artist: "Dr. Dre",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Dr. Dre - The Next Episode ft. Snoop Dogg, Kurupt, Nate Dogg.mp3",
    id: 8,
  },
  {
    title: "Escape (The Pina Colada Song)",
    artist: "Rupert Holmes",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Escape (The Pina Colada Song).mp3",
    id: 9,
  },
  {
    title: "Give It To Me",
    artist: "Timbaland",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Give It To Me.mp3",
    id: 10,
  },
  {
    title: "Just The Two of Us [HQ]",
    artist: "Grover Washington Jr.",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Grover Washington Jr. - Just The Two of Us [HQ].mp3",
    id: 11,
  },
  {
    title: "Ice Ice Baby",
    artist: "Vanilla Ice",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Ice Ice Baby.mp3",
    id: 12,
  },
  {
    title: "Immigrant Song",
    artist: "Led Zeppelin",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Immigrant Song.mp3",
    id: 13,
  },
  {
    title: "It Wasnt Me",
    artist: "Shaggy",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/It Wasnt Me.mp3",
    id: 14,
  },
  {
    title: "Its Not Unusual",
    artist: "Tom Jones",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Its Not Unusual.mp3",
    id: 15,
  },
  {
    title: "I Was Made For Lovin You",
    artist: "Kiss",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Kiss - I Was Made For Lovin You.mp3",
    id: 16,
  },
  {
    title: "U Cant Touch This (HQ)",
    artist: "MC Hammer",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/MC Hammer - U Cant Touch This (HQ).mp3",
    id: 17,
  },
  {
    title: "Mr. Blue Sky",
    artist: "Electric Light Orchestra",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Mr. Blue Sky.mp3",
    id: 18,
  },
  {
    title: "Never Gonna Give You Up (Lyrics)",
    artist: "Rick Astley",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Never Gonna Give You Up - Rick Astley (Lyrics).mp3",
    id: 19,
  },
  {
    title: "Mujeriego (Letra/Lyrics)",
    artist: "Ryan Castro",
    cover: "https://link-to-cover.jpg",
    audio: "/audio/Ryan Castro - Mujeriego (LetraLyrics).mp3",
    id: 20,
  },
];

export default songs;
